parameters:
    millwright_configuration.cache_warmer.class: Millwright\ConfigurationBundle\CacheWarmer\ConfigurationCacheWarmer

    millwright_configuration.manager.class: Millwright\ConfigurationBundle\Builder\OptionManager
    millwright_configuration.options.class: Millwright\ConfigurationBundle\Builder\Options

    millwright_configuration.cache.class: Millwright\ConfigurationBundle\Cache\ConfigCache
    millwright_configuration.array_dumper.class: Millwright\ConfigurationBundle\Cache\Dumper\ArrayDumper

    millwright_configuration.builder_helper.class: Millwright\ConfigurationBundle\Configuration\ConfigurationHelper

services:
    millwright_configuration.cache.adapter:
        class: %millwright_configuration.cache.class%
        arguments:
            - %kernel.cache_dir%
            - %kernel.debug%
            - '%kernel.name%%kernel.environment%'
            - []
        public: false

    millwright_configuration.manager:
        class: %millwright_configuration.manager.class%
        arguments:
            - @millwright_configuration.cache.adapter
            - []

    millwright_configuration.cache.warmer:
        class: %millwright_configuration.cache_warmer.class%
        arguments:
            - @millwright_configuration.manager
        tags:
            - {name: kernel.cache_warmer}

    millwright_configuration.builder_helper:
        class: %millwright_configuration.builder_helper.class%
        arguments:
            - @router
            - @annotation_reader
